### ISSUE TITLE
use 

### ISSUE THREAD

**Issue by catsay217994** [ProfOak/ascii_py#10]
root@kali:~/ascii_py/ascii_py# python3 main.py -t 1.jpg
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from .ascii import Ascii
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by ProfOak** [comment]
Hi there. The code was recently updated and this issue shouldn't happen going forward. I also recommend installing this repo as a pip package. Doing this will get you the command `ascii_py` so you don't need to be in that specific directory.

```python3 -m pip install ascii_py```

If this continues to happen let me know. I'll close this issue until then.
