### ISSUE TITLE
cool look at this video

### ISSUE THREAD

**Issue by duoduo369** [ProfOak/ascii_py#6]
this project make me remeber 2 video.
several years ago my colleague do that for fun:
first he transform video to pictures, then transform picture to word(like this project maybe), after that he write word and excel macro to genrate this two video.Oh my god.

http://tieba.baidu.com/p/681386578
http://www.bilibili.com/video/av34175/

**Comment by ProfOak** [comment]
I don't have flash installed on my computer but thank you for the kind words. :-)
