### ISSUE TITLE
Use tool name on the cli

### ISSUE THREAD

**Issue by eduardostalinho** [ProfOak/ascii_py#7]
I think I could use this tool calling `ascii_py` instead of `main.py`.

Setuptools can be used to solve this issue. And i'll give a bonus that it can be installed via a package manager like pip or can be ported to OSes package managers easier.

**Comment by ProfOak** [comment]
I've got this suggestion many times. Don't worry-- It's on my todo list. :-)

**Comment by eduardostalinho** [comment]
I have not tested yet, but thank you!
