### ISSUE TITLE
"$ python ascii_py ... " is not working

### ISSUE THREAD

**Issue by AliakseiSemchankau** [ProfOak/ascii_py#8]
Hi!

I have downloaded this project using git clone (my pip couldn't install project), but it didn't work in `$ python ascii_py...`-way, it caused mistake 

> "there is no **main**  in module."

It started work only when I removed all code from ascii.py to main.py and used it in 
`$ python ascii_py/main.py ...`-way. 
`
Did I do something wrong, or project contains mistake at current moment?

**Comment by ProfOak** [comment]
Use the following command set of commands, listed at the top of the readme under manual installation

```
git clone https://github.com/profoak/ascii_py
cd ascii_py
python3 setup.py install
```

After installing ascii py, you can run it like this

 `ascii_py input.jpg`

The example at the bottom of the readme was incorrect. Sorry about that.

What happened when you try to install it through pip? I'm curious as to why that failed.

**Comment by AliakseiSemchankau** [comment]
Yes, it works fine with 
`ascii_py ...`
It seems, that I had broken pip, which tried to use anaconda instead of system python, or something like that. I've deleted anaconda and reinstalled pip, and now it downloads project pretty. So, it was my bad about pip=)

**Comment by ProfOak** [comment]
For future reference you can use Python's specific pip by calling python with the -m flag. 

Example: `python3 -m pip`

http://linux.die.net/man/1/python

```
-m module-name
    Searches sys.path for the named module and runs the corresponding .py file as a script. 
```
